services:
  - type: web
    name: arcep-carte
    env: python
    plan: free
    # region: frankfurt  # ou une autre région proche de tes utilisateurs
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
