# Generated by Django 5.1.1 on 2024-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
    ]
