# Generated by Django 5.1.1 on 2024-11-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la commune'),
        ),
        migrations.AlterField(
            model_name='localite',
            name='localite',
            field=models.CharField(max_length=255, unique=True, verbose_name='Localité'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom du site'),
        ),
    ]
