# Generated by Django 5.1.1 on 2024-12-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la commune'),
        ),
    ]
