# Generated by Django 5.1.1 on 2024-11-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_commune_nom_alter_localite_localite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom de la commune'),
        ),
    ]
