# Generated by Django 5.1.1 on 2024-10-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='operateur',
        ),
    ]
