# Generated by Django 5.1.1 on 2024-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_commune_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom de la commune'),
        ),
    ]
