# Generated by Django 5.1.1 on 2024-10-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_site_operateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='operateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.operateur', verbose_name='Opérateur'),
            preserve_default=False,
        ),
    ]
