# Generated by Django 5.1.1 on 2024-10-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_site_operateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='avis_arcep',
        ),
        migrations.RemoveField(
            model_name='site',
            name='camouflage',
        ),
        migrations.RemoveField(
            model_name='site',
            name='date_autorisation',
        ),
        migrations.RemoveField(
            model_name='site',
            name='date_mise_en_service',
        ),
        migrations.RemoveField(
            model_name='site',
            name='description',
        ),
        migrations.RemoveField(
            model_name='site',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='site',
            name='hauteur_antenne',
        ),
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='num_dossier',
        ),
        migrations.RemoveField(
            model_name='site',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='site',
            name='operateur',
        ),
        migrations.RemoveField(
            model_name='site',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='site',
            name='proprietaire',
        ),
        migrations.RemoveField(
            model_name='site',
            name='ref_courrier',
        ),
        migrations.RemoveField(
            model_name='site',
            name='technologies',
        ),
        migrations.RemoveField(
            model_name='site',
            name='type_pylone',
        ),
    ]
