# Generated by Django 5.1.1 on 2024-10-21 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_site_avis_arcep_remove_site_camouflage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='avis_arcep',
            field=models.TextField(blank=True, null=True, verbose_name='Avis ARCEP'),
        ),
        migrations.AddField(
            model_name='site',
            name='camouflage',
            field=models.BooleanField(default=False, verbose_name='Camouflage'),
        ),
        migrations.AddField(
            model_name='site',
            name='date_autorisation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'autorisation"),
        ),
        migrations.AddField(
            model_name='site',
            name='date_mise_en_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mise en service'),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='site',
            name='emplacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.emplacement', verbose_name='Emplacement'),
        ),
        migrations.AddField(
            model_name='site',
            name='hauteur_antenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Hauteur de l'antenne"),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='site',
            name='localite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.localite', verbose_name='Localité'),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='site',
            name='num_dossier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Numéro de dossier'),
        ),
        migrations.AddField(
            model_name='site',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='site',
            name='operateur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='home.operateur', verbose_name='Opérateur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Sites/', verbose_name='Photo du site'),
        ),
        migrations.AddField(
            model_name='site',
            name='proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Propriétaire'),
        ),
        migrations.AddField(
            model_name='site',
            name='ref_courrier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Référence de courrier'),
        ),
        migrations.AddField(
            model_name='site',
            name='technologies',
            field=models.ManyToManyField(through='home.SiteTechnologie', to='home.technologie'),
        ),
        migrations.AddField(
            model_name='site',
            name='type_pylone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Type de pylône'),
        ),
    ]
