# Generated by Django 5.1.1 on 2024-10-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_site_avis_arcep_site_camouflage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='nom',
        ),
    ]
