# Generated by Django 5.1.1 on 2024-10-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_commune_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='nom',
            field=models.CharField(default='', max_length=255, verbose_name='Nom de la commune'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du site'),
        ),
    ]
