# Generated by Django 5.1.1 on 2024-10-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_commune_nom_alter_site_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nom',
            field=models.CharField(default='', max_length=255, verbose_name='Nom du site'),
            preserve_default=False,
        ),
    ]
